apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ppa-service-
nameSuffix: ""

resources:
  - ../../base

# Note: ppa-service doesn't use Kafka or PostgreSQL components

commonLabels:
  app: ppa-service
  service: ppa-service

images:
  - name: placeholder
    newName: dev.docker.system.local/elpa-ppa/ppa
    newTag: latest

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      - SERVICE_NAME=ppa-service

patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels
        value:
          app: ppa-service
      - op: replace
        path: /spec/template/metadata/labels
        value:
          app: ppa-service
          service: ppa-service
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/selector
        value:
          app: ppa-service
