apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_CLIENT_ID
          value: "$(SERVICE_NAME)-$(K8S_POD_NAME)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_CONSUMER_GROUP
          value: "$(SERVICE_NAME)-$(K8S_ENVIRONMENT_LABEL)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_OAUTH_CLIENT_ID
          value: workload-client
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_OAUTH_CLIENT_SECRET
          value: workload-secret
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_SASL_MECHANISM
          value: OAUTHBEARER
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_TOPIC_SUFFIX
          value: "-$(K8S_ENVIRONMENT_LABEL)"