apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


configMapGenerator:
- name: backend-cm
  behavior: merge
  literals:
    - POSTGRES_URL=jdbc:postgresql://vipsiae11t.system-a.local:5432/elpapgt
    - POSTGRES_USER=ZA-SVC-ELPAPG-T

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: app  