apiVersion: v1
kind: Template
metadata:
  name: ${BRANCH_NAME}replicaset-secret-template

parameters:
- description: Name of origin branch
  displayName: Branch name
  name: BRANCH_NAME
  required: true

- description: Name of mongo user.
  displayName: Name of mongo user.
  name: MONGODB_ADMIN_USER
  required: true

- description: Name of mongo user.
  displayName: Name of mongo user.
  name: MONGODB_ADMIN_PASSWORD
  required: true  

- description: Name of mongo user.
  displayName: Name of mongo user.
  name: MONGODB_USER
  required: true  

- description: Password of mongo db.
  displayName: Password of mongo db.
  name: MONGODB_PASSWORD
  required: true

- description: Name of secret.
  displayName: Name of secret.
  name: MONGODB_SECRETS_NAME
  required: true

- description: MongoDB Keyfile value.
  displayName: MongoDB Keyfile value.
  name: MONGODB_KEYFILE_VALUE
  required: true  

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${MONGODB_SECRETS_NAME}
    labels:
      branch: ${BRANCH_NAME}
  stringData:
    MONGODB_KEYFILE_VALUE: "${MONGODB_KEYFILE_VALUE}"
    MONGODB_ADMIN_USER: "${MONGODB_ADMIN_USER}"
    MONGODB_ADMIN_PASSWORD: "${MONGODB_ADMIN_PASSWORD}"
    MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
    MONGODB_USER: "${MONGODB_USER}"