apiVersion: v1
kind: Template
metadata:
  name: ${BRANCH_NAME}-opa-route-template

parameters:
  - description: Name of origin branch
    displayName: Branch name
    name: BRANCH_NAME
    required: true

  - description: The cluster url including the project subdomain.
    displayName: Project url.
    name: PROJECT_URL
    required: true

  - description: Unique Name of openshift ressource.
    displayName: Name of openshift ressource.
    name: RESOURCE_NAME
    required: true

objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${BRANCH_NAME}-opa-tls
      labels:
        app: ${RESOURCE_NAME}
        branch: ${BRANCH_NAME}
    spec:
      host: "${BRANCH_NAME}-opa-${PROJECT_URL}"
      port:
        targetPort: 8181
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: ${BRANCH_NAME}-opa