apiVersion: v1
kind: Template
metadata:
  name: pgadmin-credentials

parameters:
- description: Name of origin branch
  displayName: Branch name
  name: BRANCH_NAME
  required: true

- description: PostgreSQL Cluser name
  displayName: The name of the target PostgreSQL Cluster.
  name: CLUSTER_NAME
  required: true

- description: Username
  displayName: Name of the pgadmin user name (@signal-iduna.de) will be added.
  name: PGADMIN_USER
  required: true

- description: Password
  displayName: Password of the pgadmin user.
  name: PGADMIN_PASSWORD
  required: true

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: pgadmin-credentials-${CLUSTER_NAME}
    labels:
      branch: ${BRANCH_NAME}
  stringData:
    username: "${PGADMIN_USER}@signal-iduna.de"
    password: "${PGADMIN_PASSWORD}"
