apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: backend-cm
  behavior: merge
  literals:
    - POSTGRES_HOST=vipsiae11a.system.local
    - POSTGRES_DB_NAME=elpapga
    - POSTGRES_USER=ZA-SVC-ELPAG-A
