---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-postgresuser-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgB0KIQegtfAXJS19/IjRZW2K4kPdNz+MJZMNofCujW+MeqDnyp+VAIYv7xcuMQdlBXytbvqN84VXVKxx4CPi+8ejv7IybNzLHAPmWA2vV8ElbjAhJWTsbCpsDtnvlhUEr4uU5iIkB/uPg9XeFUL20LxPb6EMJgjhKHOGZr/AORAha0GTX7hp2vTTac7wyYlcWcbjwzFSH7RtEyIfo2OabeFxl8IepA91gtunyj5JXg+VMlmJxqRjFhR4EjXGIqBSzB+3hCyHry7h2Qif+vV+NmJi1OpqKq5GcQ4uKcMOSmdkaZJ+Ksbr/FJxR8AA9V4A9r7DHKTb8zSSdevh/CDn1jP56Y6Qit96JHXuC/FaiPzlhSF4l/Uh4PnK9T4Wcq5G7nZlKhzfbj6sNLpgiEbukyIra6O5/GTlf0YF45kk8k8PwFShi81HWNqD3Bjy8HorNZiifOAZONU7HsUlM61j3tG9k16tI26QJBu2OyC9v7VFJmgKFrPE1HtjAUGBHrNIqHldWa1APb1TFhBkNtCBC+LuCozof5T6S2JATJTb+DOBulll0FUvhEK+ChxpTUu4vFLJ4jn+NjwguGAqOeyvOgMw/3BRXzg1jde7vlMdwdMPFzmUYYKOok/tYfdJFkgkB4+/vtX3kwUKYUU4dFiGk1tOCoKiX98j4xUMdgTNpi7mM5jtIhzQwH/7H39nrA1xk5l+kKyNvnQ1SXkflHo7jI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: dev-postgresuser-secret
      namespace: elpa-elpa4
    type: Opaque
