apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
      app: hint
spec:
  selector:
    matchLabels:
      app: hint
  template:
    metadata:
      labels:
        app: hint
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "4000m"
              memory: "500Mi"      