apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elpa4
namePrefix: "dev-"
nameSuffix: "-hint"

resources:
  - ../../base

components:
  - ../../base/components/postgres
  - ../components/postgres

labels:
  - pairs:
      app: hint
      service: hint-service

images:
  - name: placeholder
    newName: docker-registry.default.svc:5000/elpa-hint-abn/hint
    newTag: 33909f4.1440

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      - SERVICE_NAME=hint
      - POSTGRES_SCHEMA=hint
      - AUTH_URL=https://employee.login.int.signal-iduna.org/

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: app
  - path: service-app-patch.yaml
    target: 
      kind: Service
      name: app
  - path: service-metrics-patch.yaml
    target: 
      kind: Service
      name: metrics

      

