apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: KAFKA_CLIENT_ID
              value: "$(SERVICE_NAME)-$(K8S_POD_NAME)"
            - name: KAFKA_CONSUMER_GROUP
              value: "$(SERVICE_NAME)-$(K8S_ENVIRONMENT_LABEL)"
            - name: KAFKA_OAUTH_CLIENT_ID
              value: workload-client
            - name: KAFKA_OAUTH_CLIENT_SECRET
              value: workload-secret
            - name: KAFKA_SASL_MECHANISM
              value: OAUTHBEARER
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: KAFKA_TOPIC_SUFFIX
              value: "-$(K8S_ENVIRONMENT_LABEL)"
