apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      sql: postgres
  template:
    metadata:
      labels:
        sql: postgres
    spec:
      containers:
        - name: app
          env:
            - name: FLYWAY_ENABLED
              value: "true"
            - name: FLYWAY_LOCATIONS
              value: "db/migration"
