apiVersion: apps/v1
kind: Deployment
metadata:
  name: app

spec:
  template:
    spec:
      containers:    
        - name: app
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-b-mongouser-secret
                  key: PASSWORD        